name: Test
on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint:check
      - name: Formatting
        run: npm run fmt:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: npm run build
      - name: Build
        run: npm run build:declarations
